name: ci-nodejs-workflow
on: 
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node }}
      - run: npm test 
      - run: node src/math.js