name: ci-nodejs-workflow
on: 
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Checkout
        uses: actions/checkout@v2 

      - name: Set up Node
        uses: actions/setup-node@v4 
        with:
          node-version: 18

      - run: npm test 
      - run: node src/math.js

      - name: Set up QEMU # Nome da step
        uses: docker/setup-qemu-action@v3 # DOCKER

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build # Usar id em outra step
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: barretot/aupair-connect:latest